# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/academy-jekyll" # the subpath of your site, e.g. /blog
url: "https://govlab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/gems

# Folder Structure
source: ./source
# sass_dir: source/css

sass:
  sourcemap: true

contentful:
  spaces:
    - cases:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        base_path: ./source
        all_entries: true
        cda_query:
          include: 10
          limit: 1000
    - resources:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: resource
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - syllabuses:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: syllabus
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - faculty:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: faculty
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - coaching_programs:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: coachingProgram
          include: 2
          limit: 1000
        base_path: ./source
    - testimonials:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: testimonial
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - projects:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: project
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - workshops:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: workshop
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - carousels:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: carousel
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - index_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: indexPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - workshops_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: workshopsPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - coaching_programs_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: coachingProgramsPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - project_clinics_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: projectClinicsPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - courses_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: coursesPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - community_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: communityPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true
    - project_gallery_page:
        space: gvpfsi7zggwe
        access_token: 3a7e015d277bfd033bc1fc10b8399e0672a3fe1729df8575db21f19e76832d64
        cda_query:
          content_type: projectGalleryPage
          include: 2
          limit: 1000
        base_path: ./source
        all_entries: true

page_gen:
  - data: 'contentful.spaces.coaching_programs.coachingProgram'
    template: 'coaching_template'
    name: 'programName'
    dir: 'coaching'

  - data: 'contentful.spaces.faculty.faculty'
    template: 'people_template'
    name: 'lastName'
    dir: 'faculty'

  - data: 'contentful.spaces.projects.project'
    template: 'project_gallery_template'
    name: 'projectName'
    dir: 'projects'

  - data: 'contentful.spaces.syllabuses.syllabus'
    template: 'syllabus_template'
    name: 'syllabusTitle'
    dir: 'syllabus'

  # - data: 'clinics'
  #   template: 'coaching_template'
  #   name: 'title'
  #   dir: '/'
